### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by milesj** [galkinrost/gulp-rev-css-url#5]
I would like to point out that this plugin does not work. In your example, you're calling `override()` after `rev()` has run, which *does* replace the URLs in the CSS. However, the giant glaring issue is that if an image/font/etc path in the CSS has changed, the CSS will be modified, which results in the original hashed CSS file being updated, instead of a new CSS with a new hash being created. This doesn't actually revision the CSS file and completely fails for any cache busting.

There is literally no way for this to work after `rev()`, as `rev()` would need to be called again to generate a new hash, but doing so causes a double hash. This also wouldn't work before `rev()` as the image/font/etc hasn't been updated with a new hash yet. 

If am I completely misunderstanding something, please let me know, as nothing I try works correctly.

**Comment by galkinrost** [comment]
it doesn't regenerate hash for modified file. And a file-hash pair is't correct, yep. But the propability of that a hash of a modified css with new urls match another hash of the same file is low, I guess.

**Comment by milesj** [comment]
That may be but as of now, this plugin is completely unusable if you want true cache busting and revisioning.

**Comment by galkinrost** [comment]
mm, why? Could you give an example when it is competely unusable, please?

**Comment by milesj** [comment]
I explained it above but I'll explain it again with steps.

1) Say we have the following hashed assets -- `styles-ajflehwod.css` and `foo-gjaldjwq.jpg` -- with the CSS file referencing the image inside of it like so: `url('../images/foo-gjaldjwq.jpg')`.
2) We update the `foo.jpg` source image.
3) We run `gulp-rev`.
4) It generates a new hashed file: `foo-ijalbnvc.jpg`.
5) We run `gulp-rev-css-url`.
6) It updates the URL in the CSS file to `url('../images/foo-ijalbnvc.jpg')`.
7) It modifies the `styles-ajflehwod.css`.

All of these steps are correct except for #7, which should generate a new CSS file with a new hash. If a new CSS file is not generated, then the updated image will never be used as browsers would have already cached the old `styles-ajflehwod.css` file (which is especially true for CloudFront which never expires files).

As of right now, this is my gulp task to get this working correctly.

```javascript
gulp.task('rev', [/*'img',*/ 'css', 'js', 'font'], function() {
    return gulp.src('./build/**/*')
        .pipe(function() {
            // We need to temporarily generate new hashes for all the files, apply the new CSS URLs, and then reset them back.
            // Most of this code was taken from gulp-rev.
            return through.obj(function(file, enc, cb) {
                if (file.isNull()) {
                    cb(null, file);
                    return;
                }

                file.revOrigPath = file.path;
                file.revOrigBase = file.base;

                var hash = file.revHash = crypto.createHash('md5').update(file.contents).digest('hex').slice(0, 8);
                var ext = path.extname(file.path);
                var filename = path.basename(file.path, ext) + '-' + hash + ext;

                file.path = path.join(path.dirname(file.path), filename);
                cb(null, file);
            });
        }())
        .pipe(cssUrl())
        .pipe(function() {
            // Reset the paths back before sending to gulp-rev.
            return through.obj(function(file, enc, cb) {
                file.path = file.revOrigPath;
                cb(null, file);
            })
        }())
        .pipe(rev())
        .pipe(gulp.dest('./public'))
        .pipe(rev.manifest())
        .pipe(gulp.dest('./'));
});
```

**Comment by galkinrost** [comment]
Oh, yes, you're right. I fixed it in the latest commit.

**Comment by milesj** [comment]
Awesome, thanks for the fix. I'll give it a try and let you know how it works.

**Comment by galkinrost** [comment]
Thanks you for the issue and awaiting your feedback
