### ISSUE TITLE
gulp-rev was switched to 10 character hash

### ISSUE THREAD

**Issue by mahnunchik** [galkinrost/gulp-rev-css-url#7]
https://github.com/sindresorhus/gulp-rev/commit/11e859ee78aa48b0a2cbb23b1c705df7616ffbd4

**Comment by galkinrost** [comment]
https://github.com/galkinrost/gulp-rev-css-url/commit/9dfddb4ef80000dc20fa2aeb2e1fb1a2b90f5ade
